"use client";
import { useEffect, useState } from "react";
import { HexColorPicker } from "react-colorful";
import { Circle, IText, Rect, FabricImage } from "fabric";
import { RxText } from "react-icons/rx";
import { LuShapes } from "react-icons/lu";
import { CgShapeCircle, CgShapeSquare } from "react-icons/cg";
import { IoMdColorFill } from "react-icons/io";
import { FaPencilAlt } from "react-icons/fa";
import { FaImages } from "react-icons/fa";

import { FabricJSCanvas, useFabricJSEditor } from "fabricjs-react";
import "../app/globals.css";

export const SlideEditor = ({
  defaultSlideData,
}: {
  defaultSlideData: any;
}) => {
  const { editor, onReady } = useFabricJSEditor();
  const [canvasState, setCanvasState] = useState([]);
  const [color, setColor] = useState("#aabbcc");
  const [currentSlide, setCurrentSlide] = useState(0);

  const slidesData = [
    {
      version: "6.7.0",
      objects: [
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 989,
          top: 148,
          width: 429,
          height: 581,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: "http://127.0.0.1:3000/1.png",
          crossOrigin: null,
          filters: [],
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "SlideySlides",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 100,
          width: 226.48,
          height: 45.2,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.1053,
          scaleY: 2.1053,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Theme: Reinventing the Wheel",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 99,
          top: 218,
          width: 587.32,
          height: 45.2,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Made by: Dhruv, Joshua, Kim, Siddharth, Siddhesh",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 81.9598,
          top: 622.2068,
          width: 957.24,
          height: 45.2,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.8007,
          scaleY: 0.8007,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Table of Contents",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 119,
          top: 125,
          width: 311.3086,
          height: 45.2,
          fill: "#ededee",
          stroke: "#ededee",
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "01",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 139,
          top: 247,
          width: 44.4922,
          height: 45.2,
          fill: "#ff4ffd",
          stroke: "#ff4ffd",
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "02",
          charSpacing: 0,
          textAlign: "left",
          styles: [
            {
              start: 0,
              end: 2,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: "#ff4ffd",
                strokeWidth: 1,
                fill: "#ff4ffd",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 139,
          top: 343,
          width: 44.4922,
          height: 45.2,
          fill: "black",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "03",
          charSpacing: 0,
          textAlign: "left",
          styles: [
            {
              start: 0,
              end: 2,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: "#ff4ffd",
                strokeWidth: 1,
                fill: "#ff4ffd",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 140,
          top: 434,
          width: 44.4922,
          height: 45.2,
          fill: "black",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "04",
          charSpacing: 0,
          textAlign: "left",
          styles: [
            {
              start: 0,
              end: 2,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: "#ff4ffd",
                strokeWidth: 1,
                fill: "#ff4ffd",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 552,
          top: 243,
          width: 44.4922,
          height: 45.2,
          fill: "black",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "05",
          charSpacing: 0,
          textAlign: "left",
          styles: [
            {
              start: 0,
              end: 2,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: "#ff4ffd",
                strokeWidth: 1,
                fill: "#ff4ffd",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 554,
          top: 328,
          width: 44.4922,
          height: 45.2,
          fill: "black",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "06",
          charSpacing: 0,
          textAlign: "left",
          styles: [
            {
              start: 0,
              end: 2,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: "#ff4ffd",
                strokeWidth: 1,
                fill: "#ff4ffd",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 555,
          top: 425,
          width: 44.4922,
          height: 45.2,
          fill: "black",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "What is Reinventing \nthe wheel?",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 219,
          top: 244,
          width: 366.8359,
          height: 97.632,
          fill: "#ffffff",
          stroke: "#ffffff",
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.7077,
          scaleY: 0.6202,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Research & \nDevelopment",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 217,
          top: 336,
          width: 235.6836,
          height: 97.632,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.6218,
          scaleY: 0.6218,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Target Audience ",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 210,
          top: 440,
          width: 300.1953,
          height: 45.2,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.7182,
          scaleY: 0.7182,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Theme Justification ",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 616,
          top: 244,
          width: 355.7031,
          height: 45.2,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.8501,
          scaleY: 0.8501,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "DEMO",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 622,
          top: 331,
          width: 120,
          height: 45.2,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.7685,
          scaleY: 0.7685,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Q&A",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 627,
          top: 428,
          width: 84.4727,
          height: 45.2,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.8391,
          scaleY: 0.8391,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "01",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 104,
          top: 107,
          width: 44.4922,
          height: 45.2,
          fill: "#e67cb9",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.8082,
          scaleY: 2.8082,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "What is Reinventing \nthe Wheel?",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 111,
          top: 266,
          width: 366.8359,
          height: 97.632,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.0655,
          scaleY: 2.0655,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "02",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 104,
          top: 107,
          width: 44.4922,
          height: 45.2,
          fill: "#e67cb9",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.8082,
          scaleY: 2.8082,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Research & \nDevelopment",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 110,
          top: 266,
          width: 235.6836,
          height: 97.632,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.0655,
          scaleY: 2.0655,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Research & Development",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 100,
          width: 478.16,
          height: 45.2,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.1053,
          scaleY: 2.1053,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "- React\n- Flutter\n- NextJS\n- Websocket\n- Gemini\n- Postgresql\n- FabricJS",
          charSpacing: 0,
          textAlign: "left",
          styles: [
            {
              start: 7,
              end: 9,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: null,
                strokeWidth: 1,
                fill: "white",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
            {
              start: 16,
              end: 18,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: null,
                strokeWidth: 1,
                fill: "white",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
            {
              start: 24,
              end: 26,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: null,
                strokeWidth: 1,
                fill: "white",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
            {
              start: 35,
              end: 37,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: null,
                strokeWidth: 1,
                fill: "white",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
            {
              start: 43,
              end: 45,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: null,
                strokeWidth: 1,
                fill: "white",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
            {
              start: 55,
              end: 57,
              style: {
                fontSize: 40,
                fontWeight: "normal",
                fontFamily: "Helvetica",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: null,
                strokeWidth: 1,
                fill: "white",
                deltaY: 0,
                textBackgroundColor: "",
                textDecorationThickness: 66.667,
              },
            },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 148,
          top: 235,
          width: 227.12,
          height: 359.792,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 953,
          top: 183,
          width: 449,
          height: 556,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: "http://127.0.0.1:3000/2.png",
          crossOrigin: null,
          filters: [],
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Research & Development",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 100,
          width: 478.16,
          height: 45.2,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.1053,
          scaleY: 2.1053,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "\n- Built with Flutter for fast cross-platform development\n\n\n- Uses the phone’s gyroscope to detect rotation/tilt\n\n\n- Sends steering data to the presentation device via WebSockets\n\n\n- Leverages Gemini API to interpret voice and decide slide transitions\n",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 522.5143,
          top: 234.6523,
          width: 1315.64,
          height: 621.952,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.6618,
          scaleY: 0.6618,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 28,
          top: 159,
          width: 478,
          height: 522,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: "http://127.0.0.1:3000/4.png",
          crossOrigin: null,
          filters: [],
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "03",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 103,
          top: 107,
          width: 44.4922,
          height: 45.2,
          fill: "#e67cb9",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.8082,
          scaleY: 2.8082,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Target Audience\n",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 110,
          top: 266,
          width: 289.082,
          height: 97.632,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.0655,
          scaleY: 2.0655,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Target Audience",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 100,
          top: 100,
          width: 310.52,
          height: 45.2,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.1053,
          scaleY: 2.1053,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 609,
          top: 401,
          width: 810,
          height: 308,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: "http://127.0.0.1:3000/3.png",
          crossOrigin: null,
          filters: [],
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "- Same users as Google Slides: educators, students, presenters\n\n\n- Aimed at people who want fun/unique control\n\n\n- Especially helpful for dynamic speakers",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 52.1682,
          top: 275.9984,
          width: 1165.2,
          height: 359.792,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.6647,
          scaleY: 0.6647,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "04",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 103,
          top: 107,
          width: 44.4922,
          height: 45.2,
          fill: "#e67cb9",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.8082,
          scaleY: 2.8082,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Did We Reinvent \nthe Wheel?\n",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 111,
          top: 266,
          width: 310.5273,
          height: 150.064,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.0655,
          scaleY: 2.0655,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "05",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 103,
          top: 107,
          width: 44.4922,
          height: 45.2,
          fill: "#e67cb9",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.8082,
          scaleY: 2.8082,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "DEMO",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 111,
          top: 266,
          width: 120,
          height: 45.2,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.0655,
          scaleY: 2.0655,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
    },
    {
      version: "6.7.0",
      objects: [
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "Q&A",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 144,
          top: 297,
          width: 87.56,
          height: 45.2,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 3.103,
          scaleY: 3.103,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 40,
          fontWeight: "normal",
          fontFamily: "Helvetica",
          fontStyle: "normal",
          lineHeight: 1.16,
          text: "06",
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          textDecorationThickness: 66.667,
          type: "IText",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 141,
          top: 80,
          width: 44.72,
          height: 45.2,
          fill: "#dd95ff",
          stroke: "#dd95ff",
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.5257,
          scaleY: 2.5257,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.7.0",
          originX: "left",
          originY: "top",
          left: 722,
          top: 96,
          width: 478,
          height: 522,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: "http://127.0.0.1:3000/4.png",
          crossOrigin: null,
          filters: [],
        },
      ],
    },
  ];

  const [showFillColorPicker, setShowFillColorPicker] = useState(false);
  const [showStrokeColorPicker, setShowStrokeColorPicker] = useState(false);
  const [showShapes, setShowShapes] = useState(false);

  useEffect(() => {
    editor?.canvas
      .loadFromJSON(defaultSlideData[0])
      .then((canvas) => canvas.requestRenderAll());
  }, [editor?.canvas, defaultSlideData]);

  const onAddCircle = () => {
    const circle = new Circle({
      radius: 50,
      stroke: "#373937",
      strokeWidth: 2,
      left: 100,
      top: 50,
    });

    editor?.canvas.add(circle);
  };
  const onAddRectangle = () => {
    const rectangle = new Rect({
      left: 100,
      top: 100,
      width: 100,
      height: 100,
      stroke: "#373937", // Border color of the rectangle
      strokeWidth: 2, // Border thickness
    });

    // Add the rectangle to the canvas
    editor?.canvas.add(rectangle);
  };
  const onAddText = () => {
    const tb = new IText("Enter a Text", {
      fontFamily: "Helvetica",
      top: 100,
      left: 100,
      borderColor: "#373937",
      fill: "white",
    });

    editor?.canvas.add(tb);
  };
  const onAddImage = async () => {
    const image = await FabricImage.fromURL("rick.jpeg");
    editor?.canvas.add(image);
  };
  const onDelete = () => {
    editor?.deleteSelected();
  };
  const onSetFillColor = () => {
    editor?.setFillColor(color);
  };
  const onSetStrokeColor = () => {
    editor?.setStrokeColor(color);
  };
  const onSetBackgroundColor = () => {
    editor?.canvas.set("backgroundColor", color);
    editor?.canvas.requestRenderAll();
  };

  const onExport = () => {
    alert("Work has been saved");
    setCanvasState(editor?.canvas.toJSON());
  };
  const onImport = (JSONObj) => {
    console.log(JSONObj);

    editor?.canvas
      .loadFromJSON(JSONObj)
      .then((canvas) => canvas.requestRenderAll());
  };

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Backspace" || event.key === "Delete") {
        console.log("hi");

        onDelete();
      } else if (event.altKey && event.key === "ß") {
        // When Alt + s is clickend
        alert("Work has been saved");
        // onExport();
      } else if (event.key === "Escape") {
        if (showFillColorPicker) setShowFillColorPicker(!showFillColorPicker);
        else if (showStrokeColorPicker)
          setShowStrokeColorPicker(!showStrokeColorPicker);
        else if (showShapes) setShowShapes(!showShapes);
      }
    };

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [onDelete]);

  return (
    <div className="h-full w-full bg-black">
      <header className="flex h-[15vh] flex-col items-start justify-around p-5">
        <div>DEVS x GDGC Hackathon Presentation</div>
        <div className="flex items-baseline">
          <div className="relative">
            <LuShapes
              size={50}
              className="rounded-t-sm p-2"
              style={{
                backgroundColor: showShapes ? "#6a7282" : "transparent",
              }}
              onClick={() => {
                if (showStrokeColorPicker)
                  setShowStrokeColorPicker(!showStrokeColorPicker);
                if (showFillColorPicker)
                  setShowFillColorPicker(!showFillColorPicker);
                setShowShapes(!showShapes);
              }}
            />
            {showShapes ? (
              <div className="absolute left-0 z-20 flex flex-col rounded-sm rounded-tl-none bg-[#795ddd] p-2">
                <div className="flex w-32">
                  <CgShapeCircle
                    size={40}
                    onClick={() => {
                      onAddCircle();
                      setShowShapes(false);
                    }}
                  />
                </div>
                <div className="flex w-32">
                  <CgShapeSquare
                    size={40}
                    onClick={() => {
                      onAddRectangle();
                      setShowShapes(false);
                    }}
                  />
                </div>
              </div>
            ) : (
              ""
            )}
          </div>
          <RxText className="p-2" onClick={onAddText} size={50} />
          <div className="relative">
            <IoMdColorFill
              size={50}
              className="rounded-t-sm p-2"
              style={{
                backgroundColor: showFillColorPicker
                  ? "#6a7282"
                  : "transparent",
              }}
              onClick={() => {
                if (showStrokeColorPicker)
                  setShowStrokeColorPicker(!showStrokeColorPicker);
                if (showShapes) {
                  setShowShapes(!showShapes);
                }
                setShowFillColorPicker(!showFillColorPicker);
              }}
            />
            {showFillColorPicker ? (
              <div className="absolute left-0 z-20 flex flex-col rounded-sm rounded-tl-none bg-[#795ddd] p-2">
                <HexColorPicker color={color} onChange={setColor} />
                <div className="mt-4 mb-2 flex items-center justify-between px-2">
                  <p>{color}</p>
                  <button
                    onClick={() => {
                      onSetFillColor();
                      setShowFillColorPicker(false);
                    }}
                    className="rounded-sm bg-black px-2 hover:cursor-pointer"
                  >
                    OK
                  </button>
                </div>
              </div>
            ) : (
              ""
            )}
          </div>
          <div className="relative">
            <FaPencilAlt
              size={50}
              className="rounded-t-sm p-2"
              style={{
                backgroundColor: showStrokeColorPicker
                  ? "#6a7282"
                  : "transparent",
              }}
              onClick={() => {
                if (showFillColorPicker)
                  setShowFillColorPicker(!showFillColorPicker);
                if (showShapes) {
                  setShowShapes(!showShapes);
                }
                setShowStrokeColorPicker(!showStrokeColorPicker);
              }}
            />
            {showStrokeColorPicker ? (
              <div className="absolute left-0 z-20 flex flex-col rounded-sm rounded-tl-none bg-[#795ddd] p-2">
                <HexColorPicker color={color} onChange={setColor} />
                <div className="mt-4 mb-2 flex items-center justify-between px-2">
                  <p>{color}</p>
                  <button
                    onClick={() => {
                      onSetStrokeColor();
                      setShowStrokeColorPicker(false);
                    }}
                    className="rounded-sm bg-black px-2 hover:cursor-pointer"
                  >
                    OK
                  </button>
                </div>
              </div>
            ) : (
              ""
            )}
          </div>
          <FaImages size={50} className="p-2" onClick={onExport} />
        </div>
      </header>
      <div className="flex w-full border-t-6 border-[#795ddd]">
        <div className="h-[85vh] w-[20%] overflow-scroll border-r-6 border-[#795ddd]">
          <div className="grid w-full grid-cols-1 gap-4 p-4 text-white">
            {slidesData.map((_, index) => (
              <div
                key={index}
                className="h-[12rem] w-full"
                onClick={() => {
                  console.log("hi");

                  onImport(slidesData[index]);
                  setCurrentSlide(index);
                }}
              >
                <div className="flex h-full w-full items-center justify-center rounded-lg border-2 border-[#373937]">
                  SLIDES {index + 1}
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="flex w-full items-center justify-center bg-[#030507] p-5">
          <FabricJSCanvas
            className="sample-canvas h-[95%] w-[95%] border-2 border-[#373937] bg-[#030507]"
            onReady={onReady}
          />
        </div>
      </div>
    </div>
  );
};
